// web/layouts/Document.tsx
import type { FC } from 'react'
import React from 'react'
import type { LayoutProps as DocumentProps } from 'ssr-types-react'
import App from './App'

const Dcoument: FC<DocumentProps> = (props: DocumentProps) => {
  const { injectState } = props
  const { injectCss, injectScript } = props.staticList ?? {}

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, viewport-fit=cover"
        />
        <meta name="theme-color" content="#000000" />
        <title>Kova</title>
        {injectCss}
      </head>
      <body>
        <div id="app">
          <App>{props.children}</App>
        </div>
        {injectState}
        {injectScript}
      </body>
    </html>
  )
}

export default Dcoument

// web/layouts/Document.vue
<template>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <!-- <meta name="theme-color" content="#000000" /> -->
      <title>{{ title }}</title>
      <slot name="viteClient" />
      <slot name="customeHeadScript" />
      <slot name="cssInject" />
    </head>
    <body>
      <div id="app">
        <slot name="children" />
      </div>
      <slot name="initialData" />
      <slot name="customeFooterScript" />
      <slot name="jsInject" />
    </body>
  </html>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  name: 'Document',
  props: {
    title: {
      type: String,
      default: '',
    },
  },
})
</script>
