// web/components/layout/index.tsx
import React, { FC } from 'react'
import { LayoutProps } from 'ssr-types-react'
import App from './App'

const Layout: FC<LayoutProps> = (props: LayoutProps) => {
  const { injectState } = props
  const { injectCss, injectScript } = props.staticList!

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="theme-color" content="#000000" />
        <title>Serverless Side Render</title>
        {injectCss}
      </head>
      <body>
        <div id="app">
          <App {...props} />
        </div>
        {injectState}
        {injectScript}
      </body>
    </html>
  )
}

export default Layout

// web/components/layout/index.vue
<template>
  <!-- 注：Layout 只会在服务端被渲染，不要在此运行客户端有关逻辑 -->
  <!-- 页面初始化数据注入内容已经过 serialize-javascript 转义 防止 xss -->
  <html>
    <head>
      <meta charSet="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="theme-color" content="#000000">
      <title>Serverless Side Render for Vue3</title>
      <slot name="viteClient" />
      <!-- 初始化移动端 rem 设置，如不需要可自行删除 -->
      <slot name="customeHeadScript" />
      <slot name="cssInject" />
    </head>
    <body>
      <div id="app">
        <slot name="children" />
      </div>
      <slot name="initialData" />
      <slot name="customeFooterScript" />
      <slot name="jsInject" />
    </body>
  </html>
</template>
